// Generated by Selenium IDE
require('chromedriver');
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const Keys = require('selenium-webdriver').Key

describe('Completacion datos cliente natural', function() {
  jest.setTimeout(300000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Completacion datos cliente natural', async function() {
    await driver.manage().window().setRect(1382, 744)
    await driver.get("https://autogestion-bancamiga-lab.herokuapp.com/")    
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("angel.alejandro08@hotmail.com")
    await driver.findElement(By.id("password")).sendKeys("angel!?*1")
    await driver.findElement(By.id("password")).sendKeys(Keys.ENTER)
    await driver.findElement(By.css(".site-menu-item:nth-child(1) > a")).click()
  })
})
