// Generated by Selenium IDE
require('chromedriver');
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC-0004', function() {
  jest.setTimeout(300000);
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC-0004: Inicio de sesión correo no existente', async function() {
    await driver.manage().window().maximize();
    await driver.get("https://autogestion-bancamiga-lab.herokuapp.com/")    
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("faker@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("fake")
    await driver.findElement(By.name("commit")).click()
    await driver.findElement(By.css(".alert")).click()    
  })
})
