// Generated by Selenium IDE
require('chromedriver');
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC-0003', function() {
    jest.setTimeout(300000);
    let driver
    let vars
    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function() {
        await driver.quit();
    })
    it('TC-0003: Inicio de sesión contraseña incorrecta', async function() {
        await driver.get("https://autogestion-bancamiga-lab.herokuapp.com/")
        await driver.manage().window().setRect(1382, 744)
        await driver.findElement(By.id("email")).click()
        await driver.findElement(By.id("email")).sendKeys("angel.alejandro08@hotmail.com")
        await driver.findElement(By.id("password")).sendKeys("123")
        await driver.findElement(By.name("commit")).click()
        await driver.findElement(By.css("ul")).click()
    })
})
