// Generated by Selenium IDE
require('chromedriver');
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC-0002', function() {
    jest.setTimeout(300000);
    let driver
    let vars
    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function() {
        await driver.quit();
    })
    it('TC-0002: Inicio de sesión sin datos [fallido]', async function() {
        driver.manage().window().maximize();
        await driver.get("https://autogestion-bancamiga-lab.herokuapp.com/")    
        await driver.findElement(By.name("commit")).click()
        await driver.findElement(By.css("ul")).click()
        await driver.findElement(By.css("li")).click()
    })
})