// Generated by Selenium IDE
require('chromedriver');
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC-0005', function() {
    jest.setTimeout(300000);
    let driver
    let vars
    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function() {
        await driver.quit();
    })
    it('TC-0005: creacion de solicitud PN', async function() {
        await driver.manage().window().maximize();       
        await driver.get("https://autogestion-bancamiga-lab.herokuapp.com/")        
        await driver.findElement(By.id("email")).click()
        await driver.findElement(By.id("email")).sendKeys("angel.alejandro08@hotmail.com")
        await driver.findElement(By.id("password")).sendKeys("angel!?*1")
        await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
        await driver.findElement(By.linkText("SOLICITAR PRODUCTO")).click()
        await driver.findElement(By.id("request_product_service_type_id")).click()
        {
          const dropdown = await driver.findElement(By.id("request_product_service_type_id"))
          await dropdown.findElement(By.xpath("//option[. = 'Productos']")).click()
        }
        await driver.findElement(By.id("request_product_service_type_id")).click()
        await driver.findElement(By.id("request_product_id")).click()
        {
          const dropdown = await driver.findElement(By.id("request_product_id"))
          await dropdown.findElement(By.xpath("//option[. = 'Cuenta Corriente Virtual Amiga']")).click()
        }
        await driver.findElement(By.id("request_product_id")).click()
        await driver.findElement(By.name("request[val_firm_type]")).click()
        await driver.findElement(By.name("request[val_firm_type]")).click()
        await driver.findElement(By.name("request[val_firm_type]")).click()
        {
          const dropdown = await driver.findElement(By.name("request[val_firm_type]"))
          await dropdown.findElement(By.xpath("//option[. = 'Mancomunada']")).click()
        }
        await driver.findElement(By.name("request[val_firm_type]")).click()
        await driver.findElement(By.id("send_id")).click()
        await driver.findElement(By.css(".site-menu-item:nth-child(2) .site-menu-title")).click()
    })
})